### ISSUE TITLE
Nodes in more than 1 cluster after clustering

### ISSUE THREAD

**Issue by pmuens** [oflisback/markov-clustering#3]
Hey @oflisback first of all. Thanks for your work on this `npm` package.

I've tried to cluster this adjacency matrix:

```
[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1 ],
  [ 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],
  [ 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0 ],
  [ 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0 ],
  [ 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
  [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]
```

I get the following result after clustering this matrix:

```
[ [ 0, 1, 2, 3, 4, 5, 6, 20 ],
  [ 7, 8, 9, 10, 11 ],
  [ 12, 13, 14, 15, 16 ],
  [ 7, 8, 9, 10, 12, 13, 14, 15, 17 ],
  [ 7, 8, 9, 10, 12, 13, 14, 15, 18, 19 ] ]
```

Here's the code I've used:

```javascript
// ... some stuff to create the adjacencyMatrix here

const preparedMatrix = math.matrix(adjacencyMatrix);

let clustered = mc.cluster(preparedMatrix, {
  expandFactor: 2,
  inflateFactor: 2,
  maxLoops: 10,
  multFactor: 2,
});
```

Am I missing something here? I read that there's a possibility that the Markov Clustering algorithm might put nodes into different clusters: https://micans.org/mcl/man/mclfaq.html#ccco although the overall probability should be pretty low...

Thanks in advance!

**Comment by oflisback** [comment]
Hi @pmuens! 

I'm glad you took the implementation for a spin, I did not end up using it myself since it didn't scale well enough for the large graphs I wanted to cluster.

Is your example matrix perhaps representing a directed graph? Because if it was an undirected graph you'd expect it to be symmetric (along its diagonal), have a look among the test cases or [https://proofwiki.org/wiki/Definition:Adjacency_Matrix](https://proofwiki.org/wiki/Definition:Adjacency_Matrix) for examples.

I haven't looked into how MCL deals with directed graphs but it's less clear how well it will deal with them: [https://micans.org/mcl/man/mclfaq.html#faq3.4](https://micans.org/mcl/man/mclfaq.html#faq3.4)

**Comment by pmuens** [comment]
Hey @oflisback!
Thank you very much for your response.

That was really helpful! Yes, the graph is directed so that might be the problem here (it's basically a dependency graph).

I'll checkout the links you posted 👍 

Thanks again!
